services:
  app:
    container_name: nf-app
    build: ../
    depends_on:
      - postgres
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ../.env

  postgres:
    image: postgres:14.2
    container_name: nf-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

volumes:
  postgres:
    driver: local
